### ISSUE TITLE
Share event links to social media

### ISSUE THREAD

**Issue by clementine-smart** [horoeka-2022/gardenz#72]
As a user, I want to easily share a link to an individual event via twitter or facebook.

[Design for the "share" icon and position](https://www.figma.com/file/QbkygWObPAOmQzMRvVV6ma/gardenz?node-id=641%3A183)

- [x] investigate twitter and facebook linking features
- [x] plan how you will implement sharing
- [x] implement a "share" functionality for each event

**Comment by ARISDY** [comment]
please review if the href provided in the anchor tag is enough or was i meant to specify the absolute url to that particular event?
