### ISSUE TITLE
Trash the daisies!!

### ISSUE THREAD

**Issue by sophia-lawler** [horoeka-2022/gardenz#93]
As you can see there are some loading daisies that flash before our eyes navigating between pages. 

I want you to investigate where this is coming from and remove them without breaking the code. you may still need to check if the page is still fetching data before rendering your JSX but there is no need to render something visual.

**Comment by ciara-doelman** [comment]
Looked at ways to fix the flash when page is loading but could not find much info apart from using a loading screen.
